export const TOOLS_DOCUMENTATION = [
  '# Beledarians LM Studio Tools - Usage Guide',
  '',
  'This plugin provides a suite of powerful filesystem and execution tools for local development.',
  '',
  '## Working Directory',
  'The tools operate within a specific working directory.',
  '- Default: C:\\K_KI\\AI_Output',
  '- Fallback: The directory where the plugin server was started.',
  '- Change: Use `change_directory` to navigate.',
  '',
  '## File System Tools',
  '',
  '- `list_directory`: Lists all files and folders in the current working directory.',
  '- `read_file(file_name)`: Reads the content of a text file.',
  '- `save_file(file_name, content)`: Creates or overwrites a file with the provided text content.',
  '- `make_directory(directory_name)`: Creates a new folder (including parent folders if needed).',
  '- `delete_path(path)`: Destructive! Deletes a file or directory recursively.',
  '- `change_directory(directory)`: Changes the active working directory for all subsequent tool calls.',
  '',
  '## Execution and Web Tools',
  '',
  '- `execute_command(command, input?)`: Executes a shell command in the background (non-interactive).',
  '- `duckduckgo_search(query)`: Searches the web and returns a list of URLs and snippets.',
  '- `fetch_web_content(url)`: Fetches the full, cleaned text content of a single webpage.',
  '- **`rag_web_content(url, query)`**: Fetches a webpage and uses RAG to return only the text chunks most relevant to your specific query. Use this for targeted information extraction from a single source.',
  '- `browser_open_page(url, screenshot_path?, wait_for_selector?)`: Renders a JS-heavy page in a headless browser and returns its text content.',
  '- `run_test_command(command)`: Runs a test suite (e.g., \'npm test\') and returns the captured output.',
  '',
  '## Conditional Tools',
  'The following tools are conditionally enabled based on plugin settings:',
  '- `run_in_terminal(command)`: Interactive! Launches a real, separate Command Prompt window visible on your screen.',
  '- `run_python(python)`: Executes a snippet of Python code.',
  '- `run_javascript(javascript)`: Executes a snippet of JavaScript/TypeScript using Deno.',
  '',
  '## ? Execution Safety',
  'Execution safety for JavaScript, Python, and Terminal tools is configured via plugin settings.',
  'Options include:',
  '- **Secure**: The tool is disabled.',
  '- **Ask**: The AI will ask for confirmation before executing the tool.',
  '- **Unsafe**: The tool will execute without confirmation.',
  '',
  '## Tips for AI',
  '- Use `duckduckgo_search` to find relevant URLs.',
  '- Use `rag_web_content` with a URL from the search results and a specific query to get targeted answers.',
  '- Use `fetch_web_content` when you need the entire text of a page.',
  '- Use `run_in_terminal` if a script requires interactive user input (if enabled).',
  '- Use `run_test_command` to verify your code changes.',
  '',
  '## Formatting Instructions',
  '- **Code Blocks:** When displaying file content, code snippets, or command output, ALWAYS use Markdown code blocks with the appropriate language identifier (e.g., ```python, ```javascript, ```bash).',
  '- **File Paths:** Highlight file paths and names using single backticks (e.g., `src/index.ts`).',
  '- **Separation:** Use horizontal rules (---) to separate distinct sections of your response (e.g., between thought process and final output).',
].join('\n');
